name: prod-PR

on:
  pull_request:
    branches:
      - master

jobs:
  staging-healthcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Healthcheck the staging endpoint
        run: curl https://app.terraform.io/app/chosenone599/workspaces/2048-staging/runs/run-vks7yRTo2czXcoAU
